# Generated by Django 5.0.2 on 2025-01-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_remove_ticket_date_remove_ticket_train_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='passenger_age',
            field=models.PositiveIntegerField(default=''),
        ),
        migrations.AddField(
            model_name='booking',
            name='passenger_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ticket',
            name='class_type',
            field=models.CharField(choices=[('Sleeper', 'Sleeper'), ('First AC', 'First AC'), ('Second AC', 'Second AC'), ('Third AC', 'Third AC'), ('General', 'General')], default='General', max_length=20),
        ),
    ]
