# Generated by Django 5.0.2 on 2025-01-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_booking_passenger_age_booking_passenger_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='passenger_age',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
