# Generated by Django 5.0.2 on 2025-01-25 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_rename_amount_transaction_total_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_id',
        ),
    ]
